server {
    listen __PORT__;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Long cache for static assets (css/js/images)
    location /assets/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location /images/ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
